version: '3.4'

services:
  spa.client:
    ports:
      - '4200:4200'

  auth.server:
    depends_on:
        - auth.data
    ports:
      - '5000:5000'
    
  auth.data:
    container_name: auth.data
    image: euphoria.auth.mssql
    build:
      context: ./AuthServer/SqlData
      dockerfile: Dockerfile
    environment:
      - SA_PASSWORD=${AUTH_SERVER_SQL_PASSWORD}
      - ACCEPT_EULA=Y

  resouce.api:
    ports:
      - '5050:5050'
    