version: '3.4'

services:

  spa.client:
    container_name: spa.client
    image: euphoria.spa.client
    build:
      context: .
      dockerfile: Spa/Dockerfile

  auth.server:
    container_name: auth.server
    image: euphoria.auth.server
    build:
      context: .
      dockerfile: AuthServer/Dockerfile
    depends_on:
      - auth.data

  auth.data:
    container_name: auth.data
    image: euphoria.auth.mssql
    build:
      context: ./AuthServer/SqlData
      dockerfile: Dockerfile

  resouce.api:
    container_name: resouce.api
    image: euphoria.resouce.api
    build:
      context: .
      dockerfile: Resource.Api/Dockerfile

  
