version: '3.4'

services:

  spa.client:
    container_name: spa.client
    image: euphoria.spa.client
    build:
      context: .
      dockerfile: Spa/Dockerfile
      args:
        - SPA_CLIENT_URLS_ARG=${SPA_CLIENT_URLS}
        - AUTH_SERVER_URLS_ARG=${AUTH_SERVER_URLS}
        - RESOURCE_API_URLS_ARG=${RESOURCE_API_URLS}
        - SPA_CLIENT_URLS_ESCAPED=${SPA_CLIENT_URLS_ESCAPED}
        - AUTH_SERVER_URLS_ESCAPED=${AUTH_SERVER_URLS_ESCAPED}
        - RESOURCE_API_URLS_ESCAPED=${RESOURCE_API_URLS_ESCAPED}
        - SPA_CLIENT_BUILD_COMMAND_ARG=${SPA_CLIENT_BUILD_COMMAND}
    environment:
      - SPA_CLIENT_URLS=${SPA_CLIENT_URLS}
      - AUTH_SERVER_URLS=${AUTH_SERVER_URLS}
      - RESOURCE_API_URLS=${RESOURCE_API_URLS}

  auth.server:
    container_name: auth.server
    image: euphoria.auth.server
    build:
      context: .
      dockerfile: AuthServer/Dockerfile    
      args:
        - SPA_CLIENT_URLS_ARG=${SPA_CLIENT_URLS}
        - AUTH_SERVER_URLS_ARG=${AUTH_SERVER_URLS}
        - RESOURCE_API_URLS_ARG=${RESOURCE_API_URLS}
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ASPNETCORE_URLS=${AUTH_SERVER_URLS}
      - SPA_CLIENT_URLS=${SPA_CLIENT_URLS}
      - AUTH_SERVER_URLS=${AUTH_SERVER_URLS}
      - RESOURCE_API_URLS=${RESOURCE_API_URLS}
      - ConnectionStrings__Default=Server=${AUTH_SERVER_SQL_SERVER};Initial Catalog=${AUTH_SERVER_SQL_CATALOG};Persist Security Info=False;User ID=sa;Password=${AUTH_SERVER_SQL_PASSWORD};MultipleActiveResultSets=False;Encrypt=false;TrustServerCertificate=False;

  resouce.api:
    container_name: resouce.api
    image: euphoria.resouce.api
    build:
      context: .
      dockerfile: Resource.Api/Dockerfile
      args:
        - SPA_CLIENT_URLS_ARG=${SPA_CLIENT_URLS}
        - AUTH_SERVER_URLS_ARG=${AUTH_SERVER_URLS}
        - RESOURCE_API_URLS_ARG=${RESOURCE_API_URLS} 
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ASPNETCORE_URLS=${RESOURCE_API_URLS}
      - SPA_CLIENT_URLS=${SPA_CLIENT_URLS}
      - AUTH_SERVER_URLS=${AUTH_SERVER_URLS}
      - RESOURCE_API_URLS=${RESOURCE_API_URLS}    

  
